USE BookStoreDB
GO
CREATE TABLE Admin
(
	Username NVARCHAR(50) PRIMARY KEY,
	Password NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NOT NULL 
)
GO
CREATE TABLE User_Credentials
(
	UId INT PRIMARY KEY,
	Username NVARCHAR(50) NOT NULL,
	Password NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NOT NULL
)
GO
CREATE TABLE User_Account_Info
(
	UId INT PRIMARY KEY FOREIGN KEY REFERENCES User_Credentials,
	Name NVARCHAR(100),
	PhoneNo NVARCHAR(10),
	ShippingAddress NVARCHAR(100),
	ActiveStatus BIT NOT NULL
)
GO