CREATE DATABASE BookStoreDB
GO
USE BookStoreDB
GO
-- Category Table
CREATE TABLE Category
(
	CId INT PRIMARY KEY,
	CName NVARCHAR(50) NOT NULL,
	CDescription NVARCHAR(50),
	CImage NVARCHAR(100) NOT NULL,
	CStatus BIT NOT NULL,
	CPosition INT NOT NULL,
	CCreatedAt DATETIME NOT NULL
)
GO
-- Book Table
CREATE TABLE Book
(
	BId INT PRIMARY KEY,
	CId INT REFERENCES Category,
	BTitle NVARCHAR(50) NOT NULL,
	BISBN NVARCHAR(50) NOT NULL,
	BYEAR DATE NOT NULL,
	BPrice MONEY NOT NULL,
	BDescription NVARCHAR(100) NOT NULL,
	BPosition INT NOT NULL,
	BStatus BIT NOT NULL,
	BImage NVARCHAR(100) NOT NULL
)
