USE BookStoreDB
GO
CREATE TABLE Cart 
(
	UId INT FOREIGN KEY REFERENCES User_Credentials,
	BId INT FOREIGN KEY REFERENCES Book,
	CONSTRAINT Pk_Cart PRIMARY KEY(UId, BId)
)
GO
CREATE TABLE Wishlist
(
	UId INT FOREIGN KEY REFERENCES User_Credentials,
	BId INT FOREIGN KEY REFERENCES Book,
	CONSTRAINT Pk_Wishlist PRIMARY KEY(UId, BId)
)
GO
