//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BookStoreDBEntities : DbContext
    {
        public BookStoreDBEntities()
            : base("name=BookStoreDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Coupon> Coupons { get; set; }
        public virtual DbSet<Coupon_Validation> Coupon_Validation { get; set; }
        public virtual DbSet<OrderInvoiceDetail> OrderInvoiceDetails { get; set; }
        public virtual DbSet<OrderItem> OrderItems { get; set; }
        public virtual DbSet<User_Account_Info> User_Account_Info { get; set; }
        public virtual DbSet<User_Credentials> User_Credentials { get; set; }
        public virtual DbSet<Wishlist> Wishlists { get; set; }
        public virtual DbSet<ShippingAddress> ShippingAddresses { get; set; }
    
        public virtual ObjectResult<usp_books_by_category_Result> usp_books_by_category(Nullable<int> cId)
        {
            var cIdParameter = cId.HasValue ?
                new ObjectParameter("CId", cId) :
                new ObjectParameter("CId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_books_by_category_Result>("usp_books_by_category", cIdParameter);
        }
    
        public virtual ObjectResult<usp_get_active_categories_Result> usp_get_active_categories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_active_categories_Result>("usp_get_active_categories");
        }
    
        public virtual ObjectResult<usp_get_categories_Result> usp_get_categories()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_categories_Result>("usp_get_categories");
        }
    
        public virtual ObjectResult<usp_get_top_books_Result> usp_get_top_books(Nullable<int> rowCount)
        {
            var rowCountParameter = rowCount.HasValue ?
                new ObjectParameter("rowCount", rowCount) :
                new ObjectParameter("rowCount", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_top_books_Result>("usp_get_top_books", rowCountParameter);
        }
    
        public virtual ObjectResult<usp_get_top_books_by_category_Result> usp_get_top_books_by_category(Nullable<int> rowCount, Nullable<int> cId)
        {
            var rowCountParameter = rowCount.HasValue ?
                new ObjectParameter("rowCount", rowCount) :
                new ObjectParameter("rowCount", typeof(int));
    
            var cIdParameter = cId.HasValue ?
                new ObjectParameter("CId", cId) :
                new ObjectParameter("CId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_top_books_by_category_Result>("usp_get_top_books_by_category", rowCountParameter, cIdParameter);
        }
    
        public virtual ObjectResult<usp_get_wishlist_by_uid_Result> usp_get_wishlist_by_uid(Nullable<int> uId)
        {
            var uIdParameter = uId.HasValue ?
                new ObjectParameter("UId", uId) :
                new ObjectParameter("UId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_wishlist_by_uid_Result>("usp_get_wishlist_by_uid", uIdParameter);
        }
    
        public virtual int usp_insert_user_credentials(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insert_user_credentials", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<usp_search_by_author_Result> usp_search_by_author(string searchTerm)
        {
            var searchTermParameter = searchTerm != null ?
                new ObjectParameter("SearchTerm", searchTerm) :
                new ObjectParameter("SearchTerm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_search_by_author_Result>("usp_search_by_author", searchTermParameter);
        }
    
        public virtual ObjectResult<usp_search_by_category_Result> usp_search_by_category(string searchTerm, Nullable<int> cId)
        {
            var searchTermParameter = searchTerm != null ?
                new ObjectParameter("SearchTerm", searchTerm) :
                new ObjectParameter("SearchTerm", typeof(string));
    
            var cIdParameter = cId.HasValue ?
                new ObjectParameter("CId", cId) :
                new ObjectParameter("CId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_search_by_category_Result>("usp_search_by_category", searchTermParameter, cIdParameter);
        }
    
        public virtual ObjectResult<usp_search_by_isbn_Result> usp_search_by_isbn(string searchTerm)
        {
            var searchTermParameter = searchTerm != null ?
                new ObjectParameter("SearchTerm", searchTerm) :
                new ObjectParameter("SearchTerm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_search_by_isbn_Result>("usp_search_by_isbn", searchTermParameter);
        }
    
        public virtual ObjectResult<usp_search_by_title_Result> usp_search_by_title(string searchTerm)
        {
            var searchTermParameter = searchTerm != null ?
                new ObjectParameter("SearchTerm", searchTerm) :
                new ObjectParameter("SearchTerm", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_search_by_title_Result>("usp_search_by_title", searchTermParameter);
        }
    
        public virtual int usp_insert_book(Nullable<int> cId, string bTitle, string bAuthor, string bISBN, Nullable<System.DateTime> bYear, Nullable<decimal> bPrice, string bDescription, Nullable<int> bPosition, string bImage)
        {
            var cIdParameter = cId.HasValue ?
                new ObjectParameter("CId", cId) :
                new ObjectParameter("CId", typeof(int));
    
            var bTitleParameter = bTitle != null ?
                new ObjectParameter("BTitle", bTitle) :
                new ObjectParameter("BTitle", typeof(string));
    
            var bAuthorParameter = bAuthor != null ?
                new ObjectParameter("BAuthor", bAuthor) :
                new ObjectParameter("BAuthor", typeof(string));
    
            var bISBNParameter = bISBN != null ?
                new ObjectParameter("BISBN", bISBN) :
                new ObjectParameter("BISBN", typeof(string));
    
            var bYearParameter = bYear.HasValue ?
                new ObjectParameter("BYear", bYear) :
                new ObjectParameter("BYear", typeof(System.DateTime));
    
            var bPriceParameter = bPrice.HasValue ?
                new ObjectParameter("BPrice", bPrice) :
                new ObjectParameter("BPrice", typeof(decimal));
    
            var bDescriptionParameter = bDescription != null ?
                new ObjectParameter("BDescription", bDescription) :
                new ObjectParameter("BDescription", typeof(string));
    
            var bPositionParameter = bPosition.HasValue ?
                new ObjectParameter("BPosition", bPosition) :
                new ObjectParameter("BPosition", typeof(int));
    
            var bImageParameter = bImage != null ?
                new ObjectParameter("BImage", bImage) :
                new ObjectParameter("BImage", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insert_book", cIdParameter, bTitleParameter, bAuthorParameter, bISBNParameter, bYearParameter, bPriceParameter, bDescriptionParameter, bPositionParameter, bImageParameter);
        }
    
        public virtual int usp_insert_category(string cName, string cDescription, string cImage, Nullable<int> cPosition, Nullable<System.DateTime> cCreatedAt)
        {
            var cNameParameter = cName != null ?
                new ObjectParameter("CName", cName) :
                new ObjectParameter("CName", typeof(string));
    
            var cDescriptionParameter = cDescription != null ?
                new ObjectParameter("CDescription", cDescription) :
                new ObjectParameter("CDescription", typeof(string));
    
            var cImageParameter = cImage != null ?
                new ObjectParameter("CImage", cImage) :
                new ObjectParameter("CImage", typeof(string));
    
            var cPositionParameter = cPosition.HasValue ?
                new ObjectParameter("CPosition", cPosition) :
                new ObjectParameter("CPosition", typeof(int));
    
            var cCreatedAtParameter = cCreatedAt.HasValue ?
                new ObjectParameter("CCreatedAt", cCreatedAt) :
                new ObjectParameter("CCreatedAt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insert_category", cNameParameter, cDescriptionParameter, cImageParameter, cPositionParameter, cCreatedAtParameter);
        }
    
        public virtual ObjectResult<usp_get_user_details_Result> usp_get_user_details(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_get_user_details_Result>("usp_get_user_details", useridParameter);
        }
    
        public virtual ObjectResult<usp_all_books_by_category_Result> usp_all_books_by_category(Nullable<int> cId)
        {
            var cIdParameter = cId.HasValue ?
                new ObjectParameter("CId", cId) :
                new ObjectParameter("CId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_all_books_by_category_Result>("usp_all_books_by_category", cIdParameter);
        }
    
        public virtual int usp_insert_shipping_address(Nullable<int> uId, string street, string city, string state, string pincode)
        {
            var uIdParameter = uId.HasValue ?
                new ObjectParameter("UId", uId) :
                new ObjectParameter("UId", typeof(int));
    
            var streetParameter = street != null ?
                new ObjectParameter("Street", street) :
                new ObjectParameter("Street", typeof(string));
    
            var cityParameter = city != null ?
                new ObjectParameter("City", city) :
                new ObjectParameter("City", typeof(string));
    
            var stateParameter = state != null ?
                new ObjectParameter("State", state) :
                new ObjectParameter("State", typeof(string));
    
            var pincodeParameter = pincode != null ?
                new ObjectParameter("Pincode", pincode) :
                new ObjectParameter("Pincode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insert_shipping_address", uIdParameter, streetParameter, cityParameter, stateParameter, pincodeParameter);
        }
    
        public virtual ObjectResult<usp_valid_coupons_Result> usp_valid_coupons(Nullable<int> uId)
        {
            var uIdParameter = uId.HasValue ?
                new ObjectParameter("UId", uId) :
                new ObjectParameter("UId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_valid_coupons_Result>("usp_valid_coupons", uIdParameter);
        }
    }
}
