//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int BId { get; set; }
        public Nullable<int> CId { get; set; }
        public string BTitle { get; set; }
        public string BAuthor { get; set; }
        public string BISBN { get; set; }
        public System.DateTime BYEAR { get; set; }
        public decimal BPrice { get; set; }
        public string BDescription { get; set; }
        public int BPosition { get; set; }
        public bool BStatus { get; set; }
        public string BImage { get; set; }
    
        public  Category Category { get; set; } //add virtuall keyword here in case we want to load category details associated with book
    }
}
