//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderInvoiceDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderInvoiceDetail()
        {
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public string OrderId { get; set; }
        public Nullable<int> UId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string ShippingAddress { get; set; }
    
        public  User_Credentials User_Credentials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<OrderItem> OrderItems { get; set; }
    }
}
