//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Account_Info
    {
        public int UId { get; set; }
        public string Name { get; set; }
        public string PhoneNo { get; set; }
        public string ShippingAddress { get; set; }
        public bool ActiveStatus { get; set; }
    
        public  User_Credentials User_Credentials { get; set; }
    }
}
